const tg=window.Telegram?.WebApp,init=tg?.initData||"",screen=document.getElementById('screen');if(tg){tg.ready();tg.expand();tg.setHeaderColor('#f3f4f6');tg.setBackgroundColor('#f3f4f6')}let me=null,size='1024x1024';
async function api(p,o={}){o.headers={...(o.headers||{}),'X-Telegram-Init-Data':init,'Content-Type':'application/json'};let r=await fetch(p,o),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||'Ошибка');return d}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function nav(s){document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.s==s));({create:create,balance:balance,history:history,profile:profile}[s])()}
function create(){screen.innerHTML=`<section class=hero><h1>Создать изображение</h1><p class=muted>Одно изображение — 🪙 1</p><div class=field>Описание</div><textarea id=p placeholder="Например: уютная кофейня в дождливом Токио..."></textarea><div class=field>Формат</div><div class=sizes><button class="size active" data-v=1024x1024>1:1</button><button class=size data-v=1536x1024>16:9</button><button class=size data-v=1024x1536>9:16</button></div><button class=primary id=g>Создать изображение · 🪙 1</button><div id=e></div></section>`;document.querySelectorAll('.size').forEach(b=>b.onclick=()=>{document.querySelectorAll('.size').forEach(x=>x.classList.remove('active'));b.classList.add('active');size=b.dataset.v});g.onclick=generate}
async function generate(){let p=document.getElementById('p').value.trim(),b=document.getElementById('g'),e=document.getElementById('e');if(!p){e.innerHTML='<div class=error>Введите описание.</div>';return}if(me.balance<1){e.innerHTML='<div class=error>Недостаточно монет.</div>';return}b.disabled=true;b.textContent='Создаём изображение…';try{let d=await api('/api/generate',{method:'POST',body:JSON.stringify({prompt:p,size})});me.balance=d.balance;document.getElementById('bal').textContent=d.balance;screen.innerHTML=`<section class=hero><h1>Готово</h1><p class=muted>Изображение создано.</p><img src="${esc(d.image_url)}" style="width:100%;border-radius:16px;margin-top:14px"><button class=primary onclick="create()">Создать ещё</button></section>`}catch(x){e.innerHTML='<div class=error>'+esc(x.message)+'</div>';b.disabled=false;b.textContent='Создать изображение · 🪙 1'}}
function balance(){screen.innerHTML=`<section class=hero><h1>Баланс</h1><p class=muted>Доступные монеты</p><div class=stat style="text-align:center;margin-top:16px"><span class=muted>Баланс</span><b>🪙 ${me.balance}</b></div></section>`}
async function history(){screen.innerHTML='<section class=hero><h1>История</h1><p class=muted>Загрузка…</p></section>';try{let d=await api('/api/history');screen.innerHTML='<section class=hero><h1>История</h1><p class=muted>Последние генерации</p></section>'+(d.items.length?d.items.map(x=>`<div class=item><b>${esc(x.prompt)}</b><div class=muted>${esc(x.size)} · ${esc(x.status)}</div>${x.image_url?`<img src="${esc(x.image_url)}">`:''}</div>`).join(''):'<div class=hero style="text-align:center;color:#81858d">История пока пустая.</div>')}catch(e){screen.innerHTML='<div class=error>'+esc(e.message)+'</div>'}}
function profile(){screen.innerHTML=`<section class=hero><h1>${esc(me.full_name||'Пользователь')}</h1><p class=muted>@${esc(me.username||'username')}</p><div class=grid><div class=stat><span class=muted>Баланс</span><b>🪙 ${me.balance}</b></div><div class=stat><span class=muted>Создано</span><b>${me.total_images}</b></div></div><div class=stat><span class=muted>Telegram ID</span><b style="font-size:16px">${me.id}</b></div></section>`}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>nav(b.dataset.s));
(async()=>{if(!init){screen.innerHTML='<section class=hero><h1>Откройте через Telegram</h1><p class=muted>Запустите приложение кнопкой из бота.</p></section>';return}try{let d=await api('/api/me');me=d.user;document.getElementById('bal').textContent=me.balance;nav('create')}catch(e){screen.innerHTML='<div class=error>'+esc(e.message)+'</div>'}})();